version: "3"
services:
  react-frontend:
    image: "quizzler-react-frontend"
    build:
      context: "./react-frontend/"
    ports:
      - "${REACT_FRONTEND_PORT}:${REACT_FRONTEND_PORT}"
    expose:
      - "${REACT_FRONTEND_PORT}"
    volumes:
      - ${PWD}/react-frontend/package.json:/app/package.json
      - ${PWD}/react-frontend/tsconfig.json:/app/tsconfig.json
      - ${PWD}/react-frontend/tsconfig.json:/app/tsconfig.node.json
      - ${PWD}/react-frontend/index.html:/app/index.html
      - ${PWD}/react-frontend/src:/app/src
    network_mode: "bridge"
    environment:
      VITE_APP_NODEJS_BACKEND_PORT: ${NODEJS_BACKEND_PORT}
  nodejs-backend:
    image: "quizzler-nodejs-backend"
    build:
      context: "./nodejs-backend"
    ports:
      - "${NODEJS_BACKEND_PORT}:${NODEJS_BACKEND_PORT}"
    expose:
      - "${NODEJS_BACKEND_PORT}"
    volumes:
      - ${PWD}/nodejs-backend/index.js:/app/index.js
      - ${PWD}/nodejs-backend/package.json:/app/package.json
      - ${PWD}/nodejs-backend/package-lock.json:/app/package-lock.json
    environment:
      NODEJS_BACKEND_PORT: ${NODEJS_BACKEND_PORT}
