version: "3"
services:
  react-frontend:
    image: "quizzler-react-frontend"
    build:
      context: "./react-frontend/"
    ports:
      - "5173:5173"
    volumes:
      - ${PWD}/react-frontend/package.json:/app/package.json
      - ${PWD}/react-frontend/tsconfig.json:/app/tsconfig.json
      - ${PWD}/react-frontend/tsconfig.json:/app/tsconfig.node.json
      - ${PWD}/react-frontend/index.html:/app/index.html
      - ${PWD}/react-frontend/src:/app/src
    network_mode: "bridge"
  nodejs-backend:
    image: "quizzler-nodejs-backend"
    build:
      context: "./nodejs-backend"
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/nodejs-backend/index.js:/app/index.js
      - ${PWD}/nodejs-backend/package.json:/app/package.json
      - ${PWD}/nodejs-backend/package-lock.json:/app/package-lock.json