name: push-react-app-to-s3-bucket
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3.3.0
      - name: Set up NodeJS version 18
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        - name: Build React app
          run: npm ci && npm run build
          working-directory: ./react-frontend
        - name: Fetch S3 bucket ARN
          run: |
            echo "S3_BUCKET_ARN=$(terraform output s3_bucket_arn)" >> $GITHUB_ENV
          working-directory: ./terraform
        - name: Push React app to S3 bucket
          run: aws s3 sync ./dist/ ${{ env.S3_BUCKET_ARN }} --delete
          working-directory: ./react-frontend
